# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{tabs_on_rails}
  s.version = ""

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Simone Carletti"]
  s.date = %q{2010-05-11}
  s.description = %q{TabsOnRails is a simple Rails plugin for creating and managing Tabs.}
  s.email = %q{weppos@weppos.net}
  s.extra_rdoc_files = [
    "LICENSE.rdoc",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "CHANGELOG.rdoc",
     "LICENSE.rdoc",
     "Manifest",
     "README.rdoc",
     "Rakefile",
     "init.rb",
     "install.rb",
     "lib/tabs_on_rails.rb",
     "lib/tabs_on_rails/controller_mixin.rb",
     "lib/tabs_on_rails/tabs.rb",
     "lib/tabs_on_rails/tabs/builder.rb",
     "lib/tabs_on_rails/tabs/tabs_builder.rb",
     "lib/tabs_on_rails/version.rb",
     "rails/init.rb",
     "test/controller_mixin_helpers_test.rb",
     "test/controller_mixin_test.rb",
     "test/controller_mixin_with_controller_test.rb",
     "test/fixtures/mixin/default.html.erb",
     "test/fixtures/mixin/with_open_close_tabs.html.erb",
     "test/tabs/builder_test.rb",
     "test/tabs/tabs_builder_test.rb",
     "test/tabs_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/atomgas/tabs_on_rails}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Rails 3 compatible ? tabs_on_rails}
  s.test_files = [
    "test/controller_mixin_helpers_test.rb",
     "test/controller_mixin_test.rb",
     "test/controller_mixin_with_controller_test.rb",
     "test/tabs/builder_test.rb",
     "test/tabs/tabs_builder_test.rb",
     "test/tabs_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

